export const GET_WATER_SENSOR_AREA_LIST = 'GET_WATER_SENSOR_AREA_LIST';
export const GET_WATER_SENSOR_AREA_LIST2 = 'GET_WATER_SENSOR_AREA_LIST2';
export const GET_WATER_SENSOR_TYPE_LIST = 'GET_WATER_SENSOR_TYPE_LIST';
