export const UPDATE_WATER_SENSOR_AREA_LIST = 'UPDATE_WATER_SENSOR_AREA_LIST';
export const UPDATE_WATER_SENSOR_AREA_LIST2 = 'UPDATE_WATER_SENSOR_AREA_LIST2';
export const UPDATE_WATER_SENSOR_TYPE_LIST = 'UPDATE_WATER_SENSOR_TYPE_LIST';
